---
blueprint:
  name: Humidity-Based Ventilation Notification
  description: |
    This blueprint monitors absolute humidity levels indoors and outdoors.
    It sends a notification when it is optimal to ventilate.

    You can get the absolute humidity levels with the custom integration [Thermal Comfort](https://github.com/dolezsa/thermal_comfort).

    This blueprint is create with the help of AI (llm mistralai/magistral-small-2509).
  domain: automation
  source_url: https://github.com/HardTy/home-assistant-config/blob/main/blueprints/humidity_based_ventilation.yaml

  input:
    sensor_outside_humidity:
      name: Outdoor Absolute Humidity Sensor
      selector:
        entity:
          filter:
            integration: thermal_comfort
            domain: sensor
          multiple: false
    sensor_inside_humidity:
      name: Indoor Absolute Humidity Sensor
      selector:
        entity:
          filter:
            integration: thermal_comfort
            domain: sensor
          multiple: false
    notification_devices:
      name: Notification Devices
      description: (e.g., mobile app)
      selector:
        device:
          entity:
            integration: mobile_app
          multiple: true
    interval_minutes:
      name: Interval Between Checks (in minutes)
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          mode: box

variables:
  outside_humidity: !input sensor_outside_humidity
  inside_humidity: !input sensor_inside_humidity
  interval_minutes: !input interval_minutes
  target_notify_devices: !input notification_devices

trigger:
  - platform: time_pattern
    minutes: "/{{ interval_minutes }}"
    id: interval_check

condition: "{{ outside_humidity < inside_humidity }}"

action:
  - repeat:
      for_each: "{{ target_notify_devices }}"
    sequence:
      - service: notify.notify
        data:
          message: "Now is a good time to ventilate! Outdoor humidity ({{ outside_humidity }}) is lower than indoor humidity ({{ inside_humidity }})."
          title: "Ventilation Recommendation"
        target: "{{ repeat.item }}"
